### ISSUE TITLE
New icon for app

### ISSUE THREAD

**Issue by mansya** [levibostian/Wendy-Android#40]
Hi, I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by levibostian** [comment]
Hello there, @mansya. I appreciate you reaching out to me. That's very kind of you. 

I would be happy for you to create a logo for this project (only if you wish, of course). I love community involvement in my projects and am very open to inviting you to collaborate with your design talents. 

This project is more of a library instead of an app. So, the logo would be used in the documentation for the project and the README for the project. 

I would love to credit you, however you wish, on the README and on future documentation for the project. 

Also, I would use the logo for [the iOS version](https://github.com/levibostian/Wendy-iOS) of this library as well. 

---

I am very open to ideas you have and inspirations. Create whatever you wish. 

If you wish to create some ideas and show them, share some of your ideas before you create, whatever you wish I am open to. 

Welcome to Wendy-Android @mansya! 🎊

**Comment by mansya** [comment]
I have design a logo for this app. do you like it ? what do you think ?
![wendy](https://user-images.githubusercontent.com/33461607/41195666-470e3f40-6c5c-11e8-8c36-e358b243dd61.png)

**Comment by levibostian** [comment]
Great work, @mansya. Thank you! 

I do enjoy the design and the unique logo. However, I do not quite understand what it is. I don't really understand the cloud and what the logo means and how it ties to the library? 

Thank you!

**Comment by mansya** [comment]
Sorry. I think the app is related to the cloud. so I will remove the cloud icon. and design more similar to libraries.

**Comment by levibostian** [comment]
Ah, I see. It can be related to the cloud, but not necessarily. It allows you to create offline-first mobile apps easier. That's the main purpose behind it. Make your apps fast without the need for loading screens.

**Comment by mansya** [comment]
what do you think ? I think this icon will be depicted with wendy apps name. because the first letter of the word wendy is the letter W so I design a logo similar to the letter W and the letter W in the icon comes from two open books.
![wendy](https://user-images.githubusercontent.com/33461607/41244631-d0d20166-6dcf-11e8-873b-b9b41f7376d5.png)

**Comment by levibostian** [comment]
Unique idea. Thanks for that. I do not feel that the logo you have presented represents the library well. Sorry about that! 

If there is anything I can do for you to help you understand the library better to creating a logo that matches the library, I would be happy to. 

Thanks for all of your hard work and talent. I appreciate your time and efforts.

**Comment by mansya** [comment]
I have uploaded all the files in this link.
https://drive.google.com/open?id=1eqo36epgFc9jIBiHohAa60UwB-t1JkVb

and I have also sent the pull requests to you. please check

**Comment by mansya** [comment]
I do not understand. will you tell me?

**Comment by levibostian** [comment]
If this helps:

Wendy allows you to create offline-first mobile apps easier. That's the main purpose behind it. It makes your apps faster for your users because you do not need to wait for data to sync in your app it is all done in the background for you. 

I already have design done that I am happy with for the project in the README. Here is the header:

![current wendy project header](https://raw.githubusercontent.com/levibostian/Wendy-Android/master/misc/wendy_logo.jpg)

And [here](https://github.com/levibostian/Wendy-Android#where-did-the-name-come-from) is the inspiration behind the name and header.
