### ISSUE TITLE
Java sample implementation

### ISSUE THREAD

**Issue by essieM** [levibostian/Wendy-Android#56]
Is there a sample implementation of this in Java as well?

**Comment by levibostian** [comment]
Thanks for asking, @essieM. Welcome to Wendy! 

At this time, no, there is not a sample in Java. Wendy is written in Kotlin and is focused on Kotlin. 

Because Kotlin and Java work really nicely together, I don't see a reason that Wendy would *not* work with Java. 

Have you tried to use Wendy with Java before? If so, feel free to make a sample app and we can put a link in the README to your sample project.

**Comment by essieM** [comment]
Thanks for your response @levibostian. 
I'll give this a try in Java.
